### ISSUE TITLE
Remove extra space at the end of each code snippet

### ISSUE THREAD

**Issue by iamthenmam** [hmcfabfive/coconut-tutorial#34]

**Comment by psharma16** [comment]
Also deal with inconsistent code snippet text sizing (see the sample iterators page with the interpreter. The first code snippet is smaller than the other two)

**Comment by psharma16** [comment]
The extra space at the end of the code snippet comes from making the </pre></div> line up. Moral of the story, don't add any tabs or returns in the middle of the highlighted code blocks, even if it looks messy.
