### ISSUE TITLE
Notify interpreter team about next() bug

### ISSUE THREAD

**Issue by iamthenmam** [hmcfabfive/coconut-tutorial#43]
Input:
x = iter(["chocolate chip", "oatmeal raisin", "sugar"])
x.next()

Output:
AttributeError: 'list_iterator' object has no attribute 'next'

We get the same error with generators (AttributeError: 'generator' object has no attribute 'next')

**Comment by evhub** [comment]
@iamthenmam This is not a bug. Coconut produces compiled Python output which can run on any Python version, but it only accepts input in Python 3 syntax. In Python 3, [iterators no longer have `.next` methods](https://www.python.org/dev/peps/pep-3114/). Instead, the proper way to get the next value of an iterator is to call the `next` function on that iterator. Thus, the correct Coconut version of the above code would be
```python
x = iter(["chocolate chip", "oatmeal raisin", "sugar"])
next(x)
````
